#!/bin/bash
# Setup script for pushing to GitHub

echo "📦 Bar Graph Clock - GitHub Setup"
echo ""
echo "Step 1: Create the repository on GitHub"
echo "   → Go to: https://github.com/new"
echo "   → Repository name: bar-graph-clock"
echo "   → Make it Public (or Private, your choice)"
echo "   → DO NOT initialize with README, .gitignore, or license"
echo "   → Click 'Create repository'"
echo ""
echo "Step 2: Once created, choose your authentication method:"
echo ""
echo "   Option A: Personal Access Token (Recommended)"
echo "   → Go to: https://github.com/settings/tokens"
echo "   → Generate new token (classic)"
echo "   → Give it 'repo' scope"
echo "   → Copy the token"
echo "   → Then run: git push -u origin main"
echo "   → When prompted for username: holtzeidler"
echo "   → When prompted for password: paste your token"
echo ""
echo "   Option B: SSH (One-time setup)"
echo "   → Run: ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "   → Copy key: pbcopy < ~/.ssh/id_ed25519.pub"
echo "   → Add to GitHub: https://github.com/settings/keys"
echo "   → Then run: git remote set-url origin git@github.com:holtzeidler/bar-graph-clock.git"
echo "   → Then run: git push -u origin main"
echo ""
read -p "Press Enter after you've created the repository on GitHub..."
